import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/home/header/Header";
import Title from "@/components/home/title/Title";
import Footer from "@/components/home/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kcal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
