import Title from "@/components/home/title/Title";
import Header from "@/components/home/header/Header";
import Footer from "@/components/home/footer/Footer";
import AboutUs from "@/components/home/about-us/About-Us";
import FollowUs from "@/components/home/follow-us/FollowUs";
import Advantages from "@/components/home/advantages/Advantages";

export const metadata = {
  title: "Kcal",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className="bg-[url('/images/vegetables-bg.jpg')] bg-no-repeat bg-cover max-h-[50%]">
        <Header />
        <Title />
      </div>
      <Advantages />
      <AboutUs />
      <FollowUs />
      <Footer />
    </>
  );
}
