import DashboardHeader from "@/components/dashboard/dashboardHeader/DashboardHeader";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex justify-between h-screen">
      <header className="min-w-[250px] border-x">
        <DashboardHeader />
      </header>
      <main className="w-full h-fit px-10 py-12">{children}</main>
      {/* <aside className="w-[350px] py-12">
        <h1>Aside</h1>
      </aside> */}
    </div>
  );
}
