export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex">
      <main>{children}</main>
    </div>
  );
}
