import DashboardHeader from "@/components/dashboard/dashboardHeader/DashboardHeader";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children, pageProps }) {
  return (
    <div className="flex justify-between h-screen bg-[#f2f4f7]">
      <header className="min-w-[250px] border-x">
        <DashboardHeader />
      </header>
      <main className="w-full h-fit px-10 py-12">{children}</main>
    </div>
  );
}
